// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLV0SkgXMEIZxs2ZJAqd2RndLGH7MIzao',
    appId: '1:975105584855:web:375b2855718c6cbce74a92',
    messagingSenderId: '975105584855',
    projectId: 'social-app-firebase-mansour',
    authDomain: 'social-app-firebase-mansour.firebaseapp.com',
    storageBucket: 'social-app-firebase-mansour.appspot.com',
    measurementId: 'G-4EC9W5QWX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkVD97COmJA2XCJgxRKKSPdA9x7Gejr-A',
    appId: '1:975105584855:android:83c89018dd9e009ce74a92',
    messagingSenderId: '975105584855',
    projectId: 'social-app-firebase-mansour',
    storageBucket: 'social-app-firebase-mansour.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe1rCHgZtzb2QbNiyMIISzOSJUsbhtknE',
    appId: '1:975105584855:ios:80887d7dfc658d34e74a92',
    messagingSenderId: '975105584855',
    projectId: 'social-app-firebase-mansour',
    storageBucket: 'social-app-firebase-mansour.appspot.com',
    androidClientId: '975105584855-emslrnrjqpvmb8edhi53mrksvdku2cc8.apps.googleusercontent.com',
    iosClientId: '975105584855-gsc2hb4di01ohsli8bspa1ba2goianeq.apps.googleusercontent.com',
    iosBundleId: 'com.flutterfirebase.abdullahcource.socialAppFirebase',
  );
}
